---
#Title: "Sanson-V-HWK1-1"
#Output: pdf_document
#Date: "2023-01-23"

#Homework 1

#Enrollment Data

#Question 1
observations=nrow(full.ma.data)
cat("total number of observations in the data set", observations)

#The total number of observations in the data set is 3,227,420. 

#Question 2
length(unique(full.ma.data$plan_type))

#There are 24 different plan_types in the data. 

#Question 3
table(full.ma.data$plan_type)
table1 <- full.ma.data %>%
  group_by(plan_type, year) %>%
  summarize(count = n()) %>%
  pivot_wider(names_from = year, values_from = count)
table1

knitr::kable(table1,
             type="html", caption = "Plan Count by Year", booktabs = TRUE)

#Question 4

table(full.ma.data$plan_type)
table2 <- full.ma.data %>%
  group_by(year, plan_type) %>%
  summarize(count = n()) %>%
  pivot_wider(names_from = year, values_from = count)
table1

knitr::kable(table2,
             type="html", caption = "Plan Count by Year", booktabs = TRUE)

#Question 5

ma_per_county<-final.data %>%
  filter(!is.na(planid) & !is.na(fips)) %>%
  filter(year>= 2008 &  year<= 2015) %>%
  group_by(year, fips)
  summarize(count= n())  %>%
  pivot_wider(names_from = year, values_from = count )
  
ma_per_county
  
graph1 <- ggplot(ma_per_county, aes(x=fips, y=count, group=year, color = year)) +
  geom_line() +
  geom_point() +
  scale_x_discrete(limits = ma_per_county$fips) +
  ggtitle("Individuals per County per Year ") +
  xlab("County FIPS")
  ylab("Number of Individuals")

graph1

data_clean <- na.omit(full.ma.data)
data_graph6 <- data_clean %>%
  group_by(county, year) %>%
  summarize(average_enroll = mean(count(contractid)))

plan.premiums
graph2<- plan.premiums %>%
  drop_na(premium) %>%
  group_by(year) %>%
  summarize(mean(premium))

graph2

#Premium Data

#Question 6
#Could not understand how to join/merge the datasets. 

#Question 7
#Given I could not complete Question 6, I could not create a graph. 

#Summary Questions

#Question 8
# Why did we drop the “800-series” plans?
#800-series plans are employer-sponsored insurance plans for their employees.
#We may have dropped the plans to avoid bias in the data versus governmental or private plans.  

#Question 9
# Why do so many plans charge a $0 premium? What does that really mean to a beneficiary?
#Many Medicare Advantage plans charge a $0 premium. However, that means that a beneficiary 
#can be charged in other ways, such as through a higher deductible, coinsurance, and co-pays. 

#Question 10
# Briefly describe your experience working with these data (just a few sentences). 
# Tell me one thing you learned and one thing that really aggravated you.

#My experience working with this data was unfortunately very extensive and confusing. 
#While I recognize that the data itself is organized, my complete inexperience with 
#R/R Studio made this process more difficult than I expected. I became agravated
#when it came to question 5, as I could not figure out how to restrict datasets or 
#effectively create a graph. However, I did learn how to peruse data to find specific 
#information. 

